replicaCount: 1

image:
  repository: docker.io/nweistra/itltknbootstrap
  tag: latest
  pullPolicy: Always

service:
  name: fastapi-webhook
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  hosts:
    - host: pac.itlusions.com
    - host: pac.itlusions.nl

