apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingressroute

spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: Host(`pac.itlusions.com`) && PathPrefix(`/hooks`)
    kind: Rule
    services:
    - name: {{ .Release.Name }}-fastapi
      port: 8080 
  tls:
    secretName: pac-itlusions-com-tls